title: |
  ![](assets/logo.png){width=8cm} \
  Uczenie Maszynowe
subtitle: 'Teoria'
author:
  - 'Joe Mama'
  - 'Mike Hawk'
  - 'Nick Ger'
  - 'Hugh Jass'
  - 'Bic Didz'
  - 'Mike Oxlong'
  - 'Geega Neega'
  - 'Sleepy "Slippy" Joe (oceń w końcu kolosy)'
  - 'TrumpGPT'
date: 'June 29, 2023'
abstract: 'Przygotujcie się na niezapomnianą przygodę z kursem z uczenia maszynowego. Kurs ten zabierze Was w podróż po klasycznych algorytmach uczenia maszynowego, które potrafią zrobić niesamowite rzeczy, takie jak regresja, klasyfikacja, klastrowanie, redukcja wymiarów i wyszukiwanie wzorców. Poznacie również tajemnice sieci neuronowych i ich różnorodne typy. Kurs ten uświadomi Wam również podstawowe problemy, które mogą Wam się nawarzyć podczas uczenia maszynowego i oświeci ich matematyczne źródła. Będziecie w stanie wybrać odpowiedni algorytm uczenia maszynowego w zależności od konkretnego zadania i dostępnych danych. Ponadto, kurs ten obejmuje tematy związane z walidacją modelu i rozwiązywaniem typowych kłopotów, które mogą Wam się przyplątać podczas trenowania modelu. Zdobędziecie umiejętność przeprowadzania walidacji modelu oraz rozwiązywania występujących bolączek.'
fontsize: 11pt
links-as-notes: true
header-includes:
  # - \usepackage[polish]{babel}
  # - \usepackage[utf8]{inputenc}
  - \usepackage[margin=2cm]{geometry}
  - \usepackage{graphicx}
  - \usepackage[export]{adjustbox}
  - \setkeys{Gin}{width=0.7\textwidth}
  - \usepackage{setspace}
  - \onehalfspacing
  - \usepackage{titlesec}
  - \titleformat{\section}[block]{\newpage\large\bfseries}{\thesection}{1em}{}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyfoot{}
  - \fancyhead{}
  - \fancyhead[L]{ \nouppercase{\leftmark} }
  - \fancyhead[R]{ \rightmark }
  - \fancyfoot[C]{\thepage}
  - \renewcommand{\headruleskip}{2mm}
  - \setlength{\headheight}{21pt}
  - \usepackage{rotating}
  - \newcommand{\bsidewaysfigure}{\begin{sidewaysfigure}[h!]}
  - \newcommand{\esidewaysfigure}{\end{sidewaysfigure}}
